# Aufruf:   cd kustomize\dev
#           kustomize build | kubectl apply -f -
#           kustomize build | kubectl delete -f -

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#bases-and-overlays
resources:
  - ../base

configMapGenerator:
  - name: schuh-env
    behavior: merge
    literals:
      - NODE_ENV=development
      - LOG_DIR=/var/log/node
      - LOG_LEVEL=debug
      - LOG_PRETTY="true"
      #- APOLLO_DEBUG="false"
      - DB_HOST=mongodb
      - DB_USER=admin
      - DB_PASS=p
      - DB_POPULATE="true"
      - DB_POPULATE_FILES="true"
      - DB_AUTO_INDEX="true"
      - K8S_TLS="false"
      - USER_PASSWORD_ENCODED=$argon2i$v=19$m=4096,t=3,p=1$c6p3obdi03al6ZuPm0/HNg$IDZWFk66uccplWqppVeH/wroiG4WByfkLwp2DizrVz0

# Umgebungsvariable, Labels, Annotationen, Images, Tags usw. ueberschreiben
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md
patchesStrategicMerge:
  - readiness.yaml

# Umgebungsvariable, Labels, Annotationen, Images, Tags usw. ueberschreiben
commonLabels:
  env: dev
