---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme

configMapGenerator:
  - name: schuh-env
    literals:
      - TZ=Europe/Berlin

commonLabels:
  app.kubernetes.io/component: appserver
  app.kubernetes.io/framework: node
  app.kubernetes.io/managed-by: kustomize

# Reihenfolge fuer die Installation der Kubernetes Ressourcen
resources:
  - serviceaccount.yaml
  - deployment.yaml
  - service.yaml
