---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: acme

configMapGenerator:
  - name: mongodb-env
    literals:
      - TZ=Europe/Berlin
      - LANG=de_DE.utf8

# Ein Secret ist z.B. ein Passwort, ein sensibler Konfigurationsparameter oder ein API-Schluessel
# Secrets koennen nur im gleichen Namespace referenziert werden
# https://github.com/kubernetes-sigs/kustomize/blob/master/examples/secretGeneratorPlugin.md
# Caveat: Codierung (encoding) vs. Verschluesselung (encryption)
# kubectl get secret mongodb --output jsonpath='{.data}' --namespace acme
# https://kubernetes.io/docs/tasks/administer-cluster/encrypt-data
# https://github.com/godaddy/kubernetes-external-secrets
# KMS-Plugins (KMS = Key Management System) fuer AWS, Azure, Google Cloud, ...
secretGenerator:
  - name: mongodb
    literals:
      - password=Change Me!

# wegen "secretKeyRef" in deployment.yaml des separaten Microservice
generatorOptions:
  disableNameSuffixHash: true

commonLabels:
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/labels
  # https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels
  component: backend
  managed-by: kustomize

# Reihenfolge fuer die Installation der Kubernetes Ressourcen
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#composing-and-customizing-resources
resources:
  - persistent-volume.yaml
  - serviceaccount.yaml
  - statefulset.yaml
  - service.yaml
  - resource-quota.yaml
