---
# https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistent-volumes
# Ein "Persistent Volume" ist "cluster-scoped" und nicht einem Namespace zugeordnet
# https://kubernetes.io/blog/2018/04/13/local-persistent-volumes-beta :
# most applications should continue to use highly available, remotely accessible, durable storage
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-data-volume
  labels:
    app: mongodb-data
spec:
  capacity:
    storage: 2Gi
  accessModes: ["ReadWriteOnce"]
  # https://kubernetes.io/docs/concepts/storage/storage-classes
  # TODO bei "hostpath" wird der Pfad fuer Windows nicht verwendet
  # https://github.com/docker/for-win/issues/5325#issuecomment-632309842
  # https://github.com/docker/for-win/issues/7023
  storageClassName: manual
  # https://kubernetes.io/docs/concepts/storage/volumes/#hostpath
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mongodb/db
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-tmp-volume
  labels:
    app: mongodb-tmp
spec:
  capacity:
    storage: 50Mi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mongodb/tmp
    type: Directory

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongodb-home-volume
  labels:
    app: mongodb-home
spec:
  capacity:
    storage: 1Gi
  accessModes: ["ReadWriteOnce"]
  storageClassName: manual
  hostPath:
    path: /run/desktop/mnt/host/c/Zimmermann/volumes/mongodb/home
    type: Directory
