# Aufruf:   cd extras\mongodb\dev
#             kustomize build | kubectl apply -f -
#             kustomize build | kubectl delete -f -

---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#bases-and-overlays
resources:
  - ../base

configMapGenerator:
  - name: mongodb-env
    behavior: merge
    literals:
      - MONGO_INITDB_ROOT_USERNAME=admin

secretGenerator:
  - name: mongodb
    behavior: merge
    envs: [secret.env]

# Umgebungsvariable, Labels, Annotationen, Images, Tags usw. ueberschreiben
# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#customizing
# https://github.com/kubernetes/community/blob/master/contributors/devel/sig-api-machinery/strategic-merge-patch.md
patchesStrategicMerge:
  - liveness.yaml
  - readiness.yaml

# https://kubernetes.io/docs/tasks/manage-kubernetes-objects/kustomization/#kustomize-feature-list
commonLabels:
  env: dev
